on: [push]

jobs:  
  Uploading-job:  
    name: 'Upload build on Sofy'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v2'
      - name: 'Upload build'
        env:
          build_path: 'fb.apk'
          subscription_key: 90212334-7E07-4AED-BD33-1AEF3FED7EAB
        uses: 'SOFYDEVELOPER/sofy-app-upload-github-action@main'        
